#!/bin/sh

# Shibby 2013
# Modified script to get themes from TD directory

SCHEME=`nvram get web_css`
if [ ! "$SCHEME" == "online" ]; then
    exit 0
fi

LOCK="/tmp/ttb.lock"

if [ -f $LOCK ]; then #skrypt w działaniu
    logger TD: Another process is already working. Exiting...
    exit 0
else
    touch $LOCK

    TTB=`nvram get ttb_css`

    if [ ! -f /www/ext/$TTB.css ]; then #brak skórki

        if [ -f /www/ext/$TTB.zip ]; then #brak skorki ale jest zip ze skorka

            unzip -o /www/ext/$TTB.zip -d /www/ext/

        else #nie ma skorki ani zipa ze skorka

            rm /www/ext/*.css /www/ext/*.zip /www/ext/*.png /www/ext/*.gif /www/ext/*.jpg
            wget http://clarkmania.github.io/ripetomato/theme/$TTB.zip -O /www/ext/$TTB.zip
            sleep 5

            if [ -f /www/ext/$TTB.zip ]; then #zip sciagniety

                unzip -o /www/ext/$TTB.zip -d /www/ext/

            else #brak zipa !!

                logger TD: Cannot download Online themes. Will try again soon...
                sleep 30
                rm $LOCK
                /usr/sbin/ttb
            fi
        fi
    fi

    rm $LOCK
fi
